# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psq < Formula
  desc "lightweight postgres monitor for the terminal"
  homepage ""
  version "1.5.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.5.0/psq_Darwin_x86_64.tar.gz"
      sha256 "285845933995d011079ccef7b9cbabe727362f6559ec3b4b80642664a641ccec"

      def install
        bin.install "psq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.5.0/psq_Darwin_arm64.tar.gz"
      sha256 "2033e2b3cea5d620effd9a9cf296bd951d5578e894a1aea5ecb47983e500f5ba"

      def install
        bin.install "psq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.5.0/psq_Linux_x86_64.tar.gz"
      sha256 "d08921b0a29e374b1fb5238e80b300f251e3a7a4e940979b28f8a98c07f852bd"
      def install
        bin.install "psq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.5.0/psq_Linux_arm64.tar.gz"
      sha256 "be63609fe3eea280e31f735d50fd2c81166cb2ed94a1fff241dc9b375418c7b6"
      def install
        bin.install "psq"
      end
    end
  end

  test do
    system "#{bin}/psq --version"
  end
end
