# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Psq < Formula
  desc "lightweight postgres monitor for the terminal"
  homepage ""
  version "1.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.2.0/psq_Darwin_x86_64.tar.gz"
      sha256 "88c0c500f6734a0fcb46921113ab508bdbbbcb0964264702e1cce714e71edbb4"

      def install
        bin.install "psq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.2.0/psq_Darwin_arm64.tar.gz"
      sha256 "9da9a643e6b45ce5bbec5c2539494ffaa9b00d8c537de2e5dfe4800ae093466b"

      def install
        bin.install "psq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.2.0/psq_Linux_x86_64.tar.gz"
      sha256 "792b7d68d998d71809b3b82eaacd5eabeae70e10d02c30719d60139ac870e5c3"
      def install
        bin.install "psq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/benjaminsanborn/psq/releases/download/v1.2.0/psq_Linux_arm64.tar.gz"
      sha256 "d9d19d76bd8670214b118912854606ed26020efd36d731b0b2fffacb408ce487"
      def install
        bin.install "psq"
      end
    end
  end

  test do
    system "#{bin}/psq --version"
  end
end
